### ISSUE TITLE
More compression algorithms?

### ISSUE THREAD

**Issue by bknowles** [jdleesmiller/jdleesmiller.github.io#1]
John -- thanks to Hacker News, I read your article at http://jdlm.info/articles/2017/05/01/compression-pareto-docker-gnuplot.html and I was very interested in your results.  I understand not wanting to test with all known available algorithms, and I appreciate your linking to the Squash page for more information on that.

But I am curious to learn more about the reasons why you chose the algorithms you did.  For example, I saw brotli on the list, but not zpaq.  I don't know whether zpaq would have done any better for your test case, but I would be very curious to see the results, especially after comparison on the Pareto Frontier.

**Comment by jdleesmiller** [comment]
Hi Brad, glad to hear that!

I'm afraid my choice of programs was not all that scientific: mainly I picked programs I had used before plus some others I had heard of on Hacker News. I have hopefully made it straightforward to add new programs to https://github.com/jdleesmiller/compare_compressors . Next time I have something to compress, I will try to add zpaq. (Unless of course you or someone else does it first --- pull requests very welcome!) Thanks for the pointer.
