### ISSUE TITLE
Mathjax not working

### ISSUE THREAD

**Issue by elbaulp** [jdleesmiller/jdleesmiller.github.io#2]
Hi, I came across your post https://github.com/jdleesmiller/jdleesmiller.github.io/blob/master/_posts/2017-09-17-counting-states-combinatorics-2048.markdown from a link on hacker news.

When I started reading it I notice mathjax is not working. They shut down their CDN so is not working anymore. I had the same problem in my blog, after trying the alternative CDN the provide and seeing it does not work either, I decided to host mathjax in my blog itself, you can see the commit here: https://github.com/elbaulp/algui91-hugo/commit/8d86243e6e50341e9b6eaa695a97db7501fff275

You should fix it.

PD: I found your post and blog very interesting. Keep it up!

Bests

**Comment by jdleesmiller** [comment]
Hi there, it looks like the blog post is already referencing the replacement CDN recommended by https://www.mathjax.org/cdn-shutting-down/, which is `cdnjs.cloudflare.com`.

You can see the script tag if you scroll down in the markdown file on GitHub.

Perhaps you have something that is blocking your access to CDNJS?

I'll close this for now.

In any case, I'm glad to hear that you found the post interesting!

**Comment by elbaulp** [comment]
cdnjs.cloudflare.com didn't work for me. I tried again, from my phone an desktop (With no blockers) Here is how I see it:

![photo_2017-09-26_10-47-12](https://user-images.githubusercontent.com/394797/30851154-0902f62e-a2a8-11e7-9d69-a5dd83d1bc64.jpg)
![a](https://user-images.githubusercontent.com/394797/30851155-0904e272-a2a8-11e7-9fda-be43c54ffac3.png)
