### ISSUE TITLE
Broken link on "The Mathematics of 2048: Counting States by Exhaustive Enumeration"

### ISSUE THREAD

**Issue by TheJakeSchmidt** [jdleesmiller/jdleesmiller.github.io#3]
The "first post" link in [footnote 1 of "The Mathematics of 2048: Counting States by Exhaustive Enumeration"](http://jdlm.info/articles/2017/12/10/counting-states-enumeration-2048.html#fn:property-3) (great post!) is broken - it points to http://jdlm.info/2017/08/05/markov-chain-2048.html instead of http://jdlm.info/articles/2017/08/05/markov-chain-2048.html.

**Comment by jdleesmiller** [comment]
Thanks! Fix incoming.
